export enum Language {
  CZECH = 'CS',
  ENGLISH = 'EN',
  SLOVAK = 'SK',
  GERMAN = 'DE',
  RUSSIAN = 'RU',
  POLISH = 'PL',
  HUNGARIAN = 'HU',
  FRENCH = 'FR',
  ROMANIAN = 'RO',
  BULGARIAN = 'BG',
  CROATIAN = 'HR',
  ITALIAN = 'IT',
  SPANISH = 'ES',
  UKRAINIAN = 'UK',
  ESTONIAN = 'EE',
  LITHUANIAN = 'LT',
  LATVIAN = 'LV',
  SLOVENIAN = 'SI',
  PORTUGUESE = 'PT',
}
